### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HadrienG** [HadrienG/InSilicoSeq#1]
# Overview

the goal of the project is to create a (meta)genomics reads simulator, i.e. a program capable of simulating realistic high-throughput sequencing data

This issue is aimed at being a todo list for the project.

- [x]  ~~Make a roadmap~~

## Simulating reads
- [ ] From a genome, output perfect reads in fastq format
- [ ] From a set of genomes, output perfect reads in fastq format given abundance parameters
- [ ] Add a simple error model
- [ ] Add a more complicated error model, (based on real read data, or literature on Illumina error model?)

## Input
- [ ] The user provides a multi-fasta file and abundance parameters
- [ ] The user provides a multi-fasta file, and choose the type of distribution
- [ ] The user chooses nothing, and random genomes from RefSeq genomes are selected

## Testing and packaging
- [ ] Add Travis integration
- [ ] Add test coverage
- [ ] Submit package to PyPi
